name: cashu
description: A flutter plugin for cashu.
version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.0
  isolate: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.cashu
        pluginClass: CashuPlugin
      ios:
        pluginClass: CashuPlugin
